version: '3.7'
services:
  nginx:
    image: nginx:1.19.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site/public:/home/public
      - ./templates:/etc/nginx/templates