baseURL = "/"
languageCode = "en-gb"
title = "Notes to Self"
theme = "tailwind-theme"
enableRobotsTXT = true

[taxonomies]
year = "year"
month = "month"

[permalinks]
post = "/posts/:year/:month/:slug/"
year = "/posts/:slug/"
month = "/posts/:slug/"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 4